import { colors } from "./game-kit";
import type { Discovery, RobotLoadout, RobotPart } from "./little-machine-types";

export const emptyRobotLoadout: RobotLoadout = {
  mobility: null,
  tool: null,
  sensor: null,
  utility: null,
};

export const robotParts: RobotPart[] = [
  {
    id: "clamp-arms",
    name: "Fixture Clamp Arms",
    shortName: "Clamp arms",
    slot: "tool",
    origin: "Helfrich Brothers",
    ability: "Grip and move heavy metal objects",
    description: "Repeatable locating geometry turned into two stubborn little industrial arms.",
    position: [-13, -7],
    accent: colors.orange,
  },
  {
    id: "sensory-scanner",
    name: "Sensory Evidence Scanner",
    shortName: "Scanner",
    slot: "sensor",
    origin: "New Food Innovation",
    ability: "Reveal evidence, provenance, and unsupported labels",
    description: "A taste-sensor probe that refuses to confuse an attractive claim with actual evidence.",
    position: [10, -7],
    accent: colors.green,
  },
  {
    id: "diagnostic-module",
    name: "Source-Grounded Diagnostic Module",
    shortName: "Diagnostics",
    slot: "utility",
    origin: "Red Hat",
    ability: "Trace failures and roll back unsafe changes",
    description: "Shows what changed, why it changed, and where the tiny emergency reverse lever lives.",
    position: [18, 7],
    accent: colors.red,
  },
  {
    id: "radio-antenna",
    name: "HeadTap Signal Antenna",
    shortName: "Radio",
    slot: "sensor",
    origin: "HeadTap",
    ability: "Tune hidden signals and wake sleeping objects",
    description: "A record needle, headphone wire, and just enough recommendation logic to find the good show.",
    position: [-11, 8],
    accent: colors.pink,
  },
  {
    id: "scoop-launcher",
    name: "Lacrosse Scoop Launcher",
    shortName: "Scoop",
    slot: "tool",
    origin: "Lacrosse",
    ability: "Catch, carry, and launch small objects",
    description: "A miniature head built to turn loose desk junk into ambitious trick shots.",
    position: [7, 15],
    accent: colors.tuftsBlue,
  },
  {
    id: "runner-kit",
    name: "Snowboard Runner Kit",
    shortName: "Runners",
    slot: "mobility",
    origin: "Snowboarding",
    ability: "Drift, grind cables, and preserve downhill momentum",
    description: "Tiny waxed runners for surfaces the original wheels were never emotionally prepared to handle.",
    position: [-7, 16],
    accent: colors.powder,
  },
  {
    id: "prediction-processor",
    name: "Backgammon Prediction Processor",
    shortName: "Prediction",
    slot: "utility",
    origin: "Backgammon",
    ability: "Preview moving cycles and likely trajectories",
    description: "It cannot see the future. It can, however, be very opinionated about the next six moves.",
    position: [-3, 5],
    accent: colors.yellow,
  },
  {
    id: "navigation-compass",
    name: "Madrid Night Compass",
    shortName: "Compass",
    slot: "utility",
    origin: "Madrid",
    ability: "Mark unexplored signals and shortcuts",
    description: "Folded from a transit map and a concert ticket that definitely survived the washing machine.",
    position: [-20, -2],
    accent: colors.blue,
  },
  {
    id: "coffee-cell",
    name: "Moka Auxiliary Cell",
    shortName: "Coffee cell",
    slot: "mobility",
    origin: "Morning ritual",
    ability: "Temporary speed and torque boost",
    description: "Technically a battery. Spiritually a second cup of coffee.",
    position: [6, -12],
    accent: colors.oxblood,
  },
];

export const desktopDiscoveries: Discovery[] = [
  {
    id: "drawing-throughput",
    title: "A fixture that survived the factory floor",
    subtitle: "Three heads in three hours became eight in forty-five minutes.",
    projectId: "helfrich",
    position: [-16, -10],
  },
  {
    id: "evidence-report",
    title: "Evidence before claims",
    subtitle: "A real product workflow for turning instrumental and sensory evidence into a reviewable decision.",
    projectId: "nfi",
    position: [9, -7],
  },
  {
    id: "rollback-note",
    title: "Speed needs a way back",
    subtitle: "Grounding, visible configuration changes, approval, and rollback made AI assistance trustworthy.",
    projectId: "red-hat",
    position: [20, 6],
  },
  {
    id: "madrid-ticket",
    title: "Music worth leaving the house for",
    subtitle: "Listening history, place, date, and distance became a recommendation system.",
    projectId: "headtap",
    position: [-11, 11],
  },
  {
    id: "field-note",
    title: "The work only counts when someone can use it",
    subtitle: "Three championships, coaching, communication, and collective repetition.",
    projectId: "lacrosse",
    position: [9, 18],
  },
];
