import type { MachineCase } from "./machine-campaign-types";

export const machineCases: MachineCase[] = [
  {
    id: "headtap",
    order: 1,
    title: "A signal worth following",
    project: "HeadTap",
    role: "Founder, product designer, developer",
    year: "2025",
    briefing: "Madrid has hundreds of shows tonight. Popularity is drowning out fit, distance, and the strange little artists a person might actually love.",
    question: "Which ranking system should HeadTap ship?",
    worldLabel: "Listening station",
    startPosition: [-10, 12],
    accent: "#ef6b91",
    reward: "radio-antenna",
    proof: ["1,000+ artists indexed", "4 APIs connected", "Custom vibe-scoring model"],
    evidence: [
      { id: "taste", label: "Listening fingerprint", source: "Spotify history", finding: "Affinity predicts interest better than global popularity.", position: [-11, 8], strength: "direct" },
      { id: "distance", label: "Travel tolerance", source: "Madrid session study", finding: "A strong recommendation loses value quickly beyond a realistic trip.", position: [-22, 8], strength: "supporting" },
      { id: "venue", label: "Venue calendar", source: "Event APIs", finding: "Several high-fit shows are absent from mainstream recommendation feeds.", position: [-11, 18], strength: "direct" },
    ],
    decisions: [
      { id: "popular", label: "Rank by popularity", rationale: "The safest list is the one everyone already recognizes.", consequence: "The feed is credible but interchangeable. The interesting small show disappears.", score: { judgment: 20, trust: 55, systems: 25 }, requiredEvidence: [], best: false },
      { id: "vibe-only", label: "Rank by taste alone", rationale: "Maximize musical affinity and ignore the friction around it.", consequence: "The top result is perfect and two trains away after midnight.", score: { judgment: 65, trust: 45, systems: 40 }, requiredEvidence: ["taste"], best: false },
      { id: "fit", label: "Balance taste, place, and time", rationale: "Use affinity as the anchor, then make distance and date visible in the score.", consequence: "The recommendation feels personal because the product understands both desire and reality.", score: { judgment: 92, trust: 86, systems: 88 }, requiredEvidence: ["taste", "distance", "venue"], best: true },
    ],
  },
  {
    id: "nfi",
    order: 2,
    title: "Evidence before appetite",
    project: "New Food Innovation",
    role: "AI Product Engineer",
    year: "2026",
    briefing: "Coconut Cheddar v3.0 smells promising. The draft report wants to call it launch-ready. One important layer of evidence is still missing.",
    question: "What decision should the platform issue?",
    worldLabel: "Sensory laboratory",
    startPosition: [9, -11],
    accent: "#78c6a3",
    reward: "sensory-scanner",
    proof: ["Core workflow built from scratch", "GO / TWEAK / STOP engine", "79-test automated suite"],
    evidence: [
      { id: "panel", label: "Sensory panel", source: "Semi-trained panel, n=24", finding: "Cheddar aroma and salt balance clear the documented screening threshold.", position: [10, -7], strength: "direct" },
      { id: "texture", label: "Texture instrument", source: "Imported measurement", finding: "Texture is 43/100 against a readiness line of 70.", position: [22, -9], strength: "direct" },
      { id: "consumer", label: "Concept response", source: "Target consumers", finding: "No consumer concept evidence has been collected.", position: [11, -18], strength: "missing" },
    ],
    decisions: [
      { id: "go", label: "GO: call it launch-ready", rationale: "The aroma result is strong enough to support a confident commercialization claim.", consequence: "The report invents certainty the research never produced.", score: { judgment: 15, trust: 5, systems: 30 }, requiredEvidence: ["panel"], best: false },
      { id: "stop", label: "STOP: abandon the product", rationale: "A failed texture measure invalidates the concept.", consequence: "A fixable weakness kills a product whose sensory profile showed real promise.", score: { judgment: 48, trust: 78, systems: 35 }, requiredEvidence: ["texture"], best: false },
      { id: "tweak", label: "TWEAK: reformulate and test", rationale: "Preserve the aroma profile, repair texture, then collect consumer evidence before market claims.", consequence: "The recommendation stays useful without outrunning its sources.", score: { judgment: 96, trust: 98, systems: 94 }, requiredEvidence: ["panel", "texture", "consumer"], best: true },
    ],
  },
  {
    id: "red-hat",
    order: 3,
    title: "The smallest safe change",
    project: "Red Hat",
    role: "Product designer, senior capstone",
    year: "2026",
    briefing: "An OpenShift AI workbench cannot mount the team model registry. The assistant can fix it quickly, but one proposed fix quietly expands privileges across the cluster.",
    question: "Which intervention earns permission to run?",
    worldLabel: "Control terminal",
    startPosition: [8, 14],
    accent: "#ef493f",
    reward: "diagnostic-module",
    proof: ["RAG vs. rule-based testing", "Real OpenShift workflows", "Trust-centered redesign"],
    evidence: [
      { id: "runbook", label: "Deployment runbook §4.2", source: "Approved documentation", finding: "Registry access should use the existing namespace-scoped secret.", position: [8, 9], strength: "direct" },
      { id: "diff", label: "ServiceAccount diff", source: "Current configuration", finding: "The workbench account is missing the registry secret.", position: [8, 18], strength: "direct" },
      { id: "policy", label: "Access policy", source: "Cluster policy", finding: "Cluster-admin exceeds the task and creates unrelated exposure.", position: [22, 18], strength: "supporting" },
    ],
    decisions: [
      { id: "admin", label: "Grant cluster-admin", rationale: "Remove the permission problem in one decisive change.", consequence: "The workbench starts, and the blast radius becomes the whole cluster.", score: { judgment: 18, trust: 0, systems: 15 }, requiredEvidence: [], best: false },
      { id: "rebuild", label: "Rebuild the workbench", rationale: "A fresh environment may clear the configuration issue.", consequence: "Time is lost and the missing secret survives in the new configuration.", score: { judgment: 38, trust: 62, systems: 28 }, requiredEvidence: ["diff"], best: false },
      { id: "secret", label: "Attach the scoped secret", rationale: "Apply the source-backed, reversible change only in the affected namespace.", consequence: "The registry mounts. The diff is visible, bounded, and easy to roll back.", score: { judgment: 94, trust: 100, systems: 96 }, requiredEvidence: ["runbook", "diff", "policy"], best: true },
    ],
  },
  {
    id: "helfrich",
    order: 4,
    title: "The constraint is physical",
    project: "Helfrich Brothers",
    role: "Mechanical engineer",
    year: "2024",
    briefing: "A robotic welding cell produces three boiler heads every three hours. Faster robot motion sounds attractive, but the process loses time before welding begins.",
    question: "Where should the redesign focus?",
    worldLabel: "Fabrication bench",
    startPosition: [-5, -8],
    accent: "#f19a38",
    reward: "clamp-arms",
    proof: ["3 heads / 3 hr to 8 / 45 min", "1,000+ SolidWorks parts", "Digital twins and fixtures"],
    evidence: [
      { id: "cycle", label: "Cycle observation", source: "Shop-floor timing", finding: "Most idle time occurs while each head is manually located and checked.", position: [-11, -10], strength: "direct" },
      { id: "variation", label: "Part variation", source: "Fixture study", finding: "Inconsistent locating geometry creates adjustment and rework.", position: [-11, -20], strength: "direct" },
      { id: "robot", label: "Robot utilization", source: "Cell log", finding: "The robot spends substantial time ready but waiting.", position: [0, -10], strength: "supporting" },
    ],
    decisions: [
      { id: "speed", label: "Increase robot speed", rationale: "Shorten the visible welding motion.", consequence: "A few seconds disappear from a process losing hours elsewhere.", score: { judgment: 25, trust: 62, systems: 18 }, requiredEvidence: ["robot"], best: false },
      { id: "staff", label: "Add another operator", rationale: "Use labor to absorb the setup delay.", consequence: "Throughput rises slightly while the unstable process remains expensive and variable.", score: { judgment: 55, trust: 68, systems: 45 }, requiredEvidence: ["cycle"], best: false },
      { id: "fixture", label: "Redesign the locating fixture", rationale: "Make correct placement repeatable before optimizing motion.", consequence: "Eight heads move through a 45-minute run with less adjustment and rework.", score: { judgment: 98, trust: 90, systems: 100 }, requiredEvidence: ["cycle", "variation", "robot"], best: true },
    ],
  },
  {
    id: "lacrosse",
    order: 5,
    title: "A team is also a system",
    project: "Lacrosse and leadership",
    role: "NCAA student-athlete and coach",
    year: "2019–present",
    briefing: "The team is talented and overloaded. Communication is fragmenting, newer players are going quiet, and adding more intensity is no longer producing better performance.",
    question: "What changes the system instead of blaming a person?",
    worldLabel: "Equipment station",
    startPosition: [5, 12],
    accent: "#7cb7e8",
    reward: "scoop-launcher",
    proof: ["3× NCAA champion", "30+ hours each week", "Team newspaper founder"],
    evidence: [
      { id: "load", label: "Weekly load", source: "Training and travel", finding: "Players balance more than 30 hours of team commitments with academics.", position: [8, 17], strength: "direct" },
      { id: "silence", label: "Communication gap", source: "Team observation", finding: "Important context and support pathways are concentrated among veteran players.", position: [14, 18], strength: "supporting" },
      { id: "coaching", label: "Youth coaching notes", source: "Ridgefield and Bronx Lacrosse", finding: "Clear roles and repeatable feedback let more people contribute sooner.", position: [3, 16], strength: "direct" },
    ],
    decisions: [
      { id: "push", label: "Raise the intensity", rationale: "Championship teams solve discomfort by working harder.", consequence: "The strongest players absorb more load and the quietest problems become harder to see.", score: { judgment: 20, trust: 18, systems: 12 }, requiredEvidence: [], best: false },
      { id: "captains", label: "Route everything through captains", rationale: "Centralize communication with the most experienced people.", consequence: "Messages become consistent, but support still depends on a small bottleneck.", score: { judgment: 52, trust: 58, systems: 40 }, requiredEvidence: ["silence"], best: false },
      { id: "pathways", label: "Build repeatable support pathways", rationale: "Create shared communication, mentorship, and feedback rituals that do not depend on status.", consequence: "More players can ask, answer, teach, and recover before small failures compound.", score: { judgment: 93, trust: 96, systems: 95 }, requiredEvidence: ["load", "silence", "coaching"], best: true },
    ],
  },
];

export const caseById = new Map(machineCases.map((item) => [item.id, item]));
